import Articles from "@/components/Articles";
import HomeLayout from "@/components/Layout/HomeLayout";
import Head from "next/head";
// import Image from "next/image";
import { ReactElement } from "react";

import { getArticles } from '../server'
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
	return (
		<>
			<Head>
				<title>山海行</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Articles data={getArticles()} />
		</>
	// <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
	);
};

Home.getLayout = function getLayout (page: ReactElement){
	return (<HomeLayout>
		{page}
	</HomeLayout>)
}

export default Home;
