import Articles from "@/components/Articles";
import HomeLayout from "@/components/Layout/HomeLayout";
import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";

import { getArticles } from '../server'

const Home: NextPage = () => {
  return (
    <HomeLayout>
      <Head>
        <title>山海行</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Articles data={getArticles()} />
      
    </HomeLayout>

    // <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  );
};

export default Home;
