import HomeLayout from "@/components/Layout/HomeLayout";
import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";

const Home: NextPage = () => {
  return (
    <HomeLayout>
      <Head>
        <title>山海行</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </HomeLayout>

    // <div className={styles.container}>
    //   <HomeLayout>
    //     填写内容
    //   </HomeLayout>

    //   <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    // </div>
  );
};

export default Home;
